sonar.projectKey=sistema-loja-web
sonar.projectName=Sistema Loja Web
sonar.projectVersion=1.0

sonar.sources=produto-service/src/main/java,pedido-service/src/main/java,api-gateway/src/main/java
sonar.tests=produto-service/src/test/java,pedido-service/src/test/java

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=\
  produto-service/target/site/jacoco/jacoco.xml,\
  pedido-service/target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/DataLoader.java,\
  **/*Application.java,\
  **/dto/**,\
  **/mapper/**

sonar.sourceEncoding=UTF-8
