spring.datasource.url=jdbc:postgresql://localhost:5434/pedido_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.br.com.infnet=DEBUG
app.seed.enabled=true
produto.service.url=http://localhost:8081

management.endpoint.health.show-details=always
