spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${PEDIDO_DB_PORT:5434}/pedido_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.br.com.infnet=DEBUG
app.seed.enabled=true

management.endpoint.health.show-details=always
